### ISSUE TITLE
Windows DLLs need VCRUNTIME140.DLL

### ISSUE THREAD

**Issue by gosanefr** [arkhipov/temporal_tables#16]
Please add a note stating that current Windows DLL require VCRUNTIME140.DLL are installed. This is provided by the Visual C++ Redistributable for Visual Studio 2015 downloadable from Microsoft here : 

https://www.microsoft.com/en-US/download/details.aspx?id=48145

**Comment by arkhipov** [comment]
This issue seems to be already fixed in 1.1.0. Have you tried [master builds on AppVeyor](https://ci.appveyor.com/project/arkhipov/temporal-tables)?

**Comment by mlt** [comment]
I think this can be closed. It was fixed indeed. Also I checked that current 9.6 beta also still uses 120 platform.

**Comment by gosanefr** [comment]
It's not a bug that needs to be fixed : the binaries are what they are but `temporal_tables-1.0.2` (the "latest" as referenced here : https://github.com/arkhipov/temporal_tables/releases/latest ) are linked to VCRUNTIME140.DLL so you need this installed on the server in order to `CREATE EXTENSION` (or you get an "Unknown error 126" IIRC)

I don't know where to get the 1.1.0 build (I see the logs on AppVeyor but no download link).

**Comment by mlt** [comment]
@gosanefr The one in *Releases* on GitHub is outdated in this sense. AppVeyor calls it *artifact*. Choose your configuration and click on *ARTIFACTS* in top right corner.

@arkhipov There is a way to push artifacts into github *Releases* section upon successful build. I never attempted that and it seems might be cluttering github's download section. But IIRC there is a way to push binaries for tagged commits only.

**Comment by gosanefr** [comment]
@mlt Thanks, found the artifacts. Unfortunately, I need x86 builds.

**Comment by arkhipov** [comment]
I have just released the 1.1.0 version. @gosanefr, could you please check if it works for you?

**Comment by gosanefr** [comment]
It's perfect, thank you.
