### ISSUE TITLE
Release plan for 1.1.0

### ISSUE THREAD

**Issue by dzolo** [arkhipov/temporal_tables#18]
Hi, first of all thanks for the great extension!

Are there any plans for releasing of the 1.1.0 version?
We are currently using the master version with manual instalation (without any issues).
But manual installation is not comfortable as PGXN..

**Comment by arkhipov** [comment]
Hello, @dzolo 

The 1.1.0 version is due for release this weekend.

**Comment by dzolo** [comment]
Perfect, thanks!

**Comment by arkhipov** [comment]
The 1.1.0 version has been released, so I am closing the issue.
