### ISSUE TITLE
Can't install on Windows 10 x64 - PG 9.5.3

### ISSUE THREAD

**Issue by pnomolos** [arkhipov/temporal_tables#19]
Installed via the graphical installer here: http://www.bigsql.org/postgresql/installers.jsp

Followed the instructions in the README, when I run `CREATE EXTENSION temporal_tables` I get the following error back:

```ERROR:  could not load library "E:/Postgres/pg95/../pg95/lib/postgresql/temporal_tables.dll": The specified procedure could not be found.```

**Comment by mlt** [comment]
Works for me with bigsql-9.5.3-4a-win64.zip and [this build](https://ci.appveyor.com/project/arkhipov/temporal-tables/build/job/t9uu4ohih1g77lp4/artifacts). Note that these guys use non-standard paths.

**Comment by pnomolos** [comment]
Could I be missing a dependency from an SDK or something that you have
installed?

**Comment by mlt** [comment]
> Could I be missing a dependency

This is highly possible. It looks like they build everything with MinGW while PG from Enterprise DB as well as this extension use MS VC++.

[Dependency walker](https://chocolatey.org/packages/dependencywalker) might help.

This extension is built using v120 platform. Probably, https://www.microsoft.com/en-us/download/details.aspx?id=40784

**Comment by pnomolos** [comment]
@mlt Thanks, the build you linked worked fine while the one linked from the README doesn't.
