### ISSUE TITLE
Cannot install on Postgres 9.6

### ISSUE THREAD

**Issue by Klobersaurus** [arkhipov/temporal_tables#23]
When installing the official 1.1.0 release, I'm receiving an error that says:
"extension could not load library" and "the specified procedure could not be found"

Pulling the artifacts from 
https://ci.appveyor.com/project/arkhipov/temporal-tables/build/job/92hel2qrm40bjwat/artifacts

This seems to install fine, but I have not tested the usability yet.
Is it recommended to use these artifacts?
Can we expect an official release for postgres 9.6 support?

**Comment by arkhipov** [comment]
I have not tested it on Windows with the latest PostgreSQL 9.6. I will try changing the version in the CI build from beta to release and see what happens.

**Comment by arkhipov** [comment]
Try the artifacts from [here](https://ci.appveyor.com/project/arkhipov/temporal-tables/build/1.0.26). The next minor release will be this weekend.

**Comment by Klobersaurus** [comment]
Thanks!  I'll give these artifacts a shot as soon as I can.
