### ISSUE TITLE
Install fails with PostgreSQL 9.4.1 on Mac OS 10.10

### ISSUE THREAD

**Issue by aexmachina** [arkhipov/temporal_tables#3]
Thanks for the extension, it looks to be exactly what we're looking for. I'm having some problems following the install instructions though, although it may just be that `make installcheck` doesn't work until after you've run `make install`.

`make` works fine, but I get failures on `make installcheck`.

```
+ ERROR:  could not open extension control file "/usr/local/Cellar/postgresql/9.4.1/share/postgresql/extension/temporal_tables.control": No such file or directory
```

So I copied files into `postgresql/extension/` until it was happy (eventually `cp temporal_tables* /usr/local/Cellar/postgresql/9.4.1/share/postgresql/extension/`) and now have the following error:

```
+ ERROR:  could not access file "$libdir/temporal_tables": No such file or directory
```

However if I run `make install` before `make installcheck` then all the tests pass.

**Comment by arkhipov** [comment]
Thank you for reporting this issue. Certainly, `make installcheck` should be run only after you have run `make install`.

**Comment by aexmachina** [comment]
Yes, the code in the README and in the tutorial you sent me both indicate that it should work before running `make install`.

**Comment by arkhipov** [comment]
Fixed.

**Comment by ShaheensWeb** [comment]
How was this solved, getting a similar error.

**Comment by ShaheensWeb** [comment]
Caused by: org.postgresql.util.PSQLException: ERROR: could not access file "$libdir/temporal_tables": No such file or directory, even though it does exist.
