### ISSUE TITLE
Is it possible to exclude some columns from being considered by versioning?

### ISSUE THREAD

**Issue by exhuma** [arkhipov/temporal_tables#42]
I have a table containing meta-information about network devices. One such information is a timestamp when the device was last seen on the network. This value is updated regularly, and as such would trigger a new history entry every time the device is polled even if nothing else has changed.

At the moment I am working on implementing a history of changes to these devices and came across temporal tables which does exactly what I want.

Unfortunately the issue explained above will create plenty of useless revisions.

I could move the column from the DB into a separate table and reference it, but that would become quite cumbersome as the value is used as a filter in almost all application query.

It would help a lot if I could simply ignore that column from the versioning process.

**Comment by mlt** [comment]
I think you can mimic this behavior using [WHEN](https://www.postgresql.org/docs/9.6/sql-createtrigger.html) clause. However, you'd need to check OLD.col vs NEW.col for those *col*s you would want the trigger to fire rather than excluding those you are not interested in.

**Comment by mlt** [comment]
Works for me. Perhaps it can be closed. One would need 2 separate triggers: for insert & delete and another one for updates.

On a side note, it would be better to place *last seen* in a separate table.

**Comment by exhuma** [comment]
I agree. There are workarounds and this can be closed.
