### ISSUE TITLE
Error with Postgresql 12 beta1

### ISSUE THREAD

**Issue by mbande** [arkhipov/temporal_tables#47]
after ```make``` and ```make install```, trying to create extension:
```
# create extension temporal_tables ;
psql: ERROR:  could not load library "/usr/lib/postgresql/12/lib/temporal_tables.so": /usr/lib/postgresql/12/lib/temporal_tables.so: undefined symbol: heap_openrv
```

**Comment by jingfeng-aa** [comment]
encounter the similar issues, it seems that some macros should be used and some macroes are renamed.

`diff --git a/versioning.c b/versioning.c
index 5d03492..338bdf3 100644
--- a/versioning.c
+++ b/versioning.c
@@ -33,6 +33,11 @@
 
 #include "temporal_tables.h"
 
+#if PG_VERSION_NUM >= 120000
+#include "access/table.h"
+#include "access/relation.h"
+#endif
+
 #if defined(_MSC_VER) && (_MSC_VER < 1800)
 #define nextafter(x, y) _nextafter(x, y)
 #endif
@@ -246,7 +251,7 @@ versioning(PG_FUNCTION_ARGS)
 						period_attname,
 						RelationGetRelationName(relation))));
 
-	period_attr = tupdesc->attrs[period_attnum - 1];
+	period_attr = TupleDescAttr(tupdesc, period_attnum - 1);
 
 	/* Check that system period attribute is not dropped. */
 	if (period_attr->attisdropped)
@@ -499,7 +504,7 @@ fill_versioning_hash_entry(VersioningHashEntry *hash_entry,
 		int					 history_attnum;
 		char				*attname;
 
-		attr = tupdesc->attrs[i];
+		attr = TupleDescAttr(tupdesc, i);
 
 		if (attr->attisdropped)
 			continue;
@@ -511,7 +516,7 @@ fill_versioning_hash_entry(VersioningHashEntry *hash_entry,
 		if (history_attnum < 0)
 			continue;
 
-		history_attr = history_tupdesc->attrs[history_attnum - 1];
+		history_attr = TupleDescAttr(history_tupdesc, history_attnum - 1);
 
 		check_attr_type(attr, history_attr, relation, history_relation);
 
@@ -759,8 +764,11 @@ deserialize_system_period(HeapTuple tuple,
 						period_attname,
 						RelationGetRelationName(relation))));
 
+#if PG_VERSION_NUM >= 120000
+	system_period = DatumGetRangeTypeP(datum);
+#else
 	system_period = DatumGetRangeType(datum);
-
+#endif
 	range_deserialize(typcache, system_period, lower, upper, &empty);
 
 	if (empty || !upper->infinite)
@@ -877,7 +885,11 @@ static HeapTuple
 modify_tuple(Relation rel, HeapTuple tuple, int period_attnum, RangeType *range)
 {
 	int			 colnum[1] = { period_attnum };
+#if PG_VERSION_NUM >= 120000
+	Datum		 values[1] = { RangeTypePGetDatum(range) };
+#else
 	Datum		 values[1] = { RangeTypeGetDatum(range) };
+#endif
 #if PG_VERSION_NUM >= 100000
 	bool		 nulls[1] = { false };
 	return heap_modify_tuple_by_cols(tuple, RelationGetDescr(rel), 1, colnum, values, nulls);`
