### ISSUE TITLE
Install temporal_tables in PostgreSQL 11.7 on Windows 10 Pro (x64)

### ISSUE THREAD

**Issue by Jay2010** [arkhipov/temporal_tables#50]
Hello,

I am trying to install the **temporal_tables extension in Windows 10 Professional**. I am using PostgreSQL 11.7 and I have been searching high and low for a way to do this in Windows but all I've found have been installation instructions for Linux.

Thanks for your assistance,

Jay2010

**Comment by mlt** [comment]
https://github.com/mlt/temporal_tables/releases

Also consider https://github.com/xocolatl/periods

**Comment by arkhipov** [comment]
There are DLLs attached in 1.2.1 version for PG 9.3-15.
